import { type NextPage } from 'next';
import Head from 'next/head';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import {
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  useUser,
} from '@clerk/nextjs';

import { type RouterOutputs, api } from '~/utils/api';
import Image from 'next/image';
import Spinner from '~/components/Spinner';
import { useRef } from 'react';
import { toast } from 'react-hot-toast';

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  const form = useRef<HTMLFormElement>(null);
  const input = useRef<HTMLInputElement>(null);
  const ctx = api.useContext();
  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess() {
      form.current?.reset();
      input.current?.focus();
      void ctx.posts.getAll.invalidate();
    },
    onError(error) {
      const message = error.data?.zodError?.fieldErrors.content;
      if (message?.[0]) toast.error(message[0]);
      else toast.error('Failed to post. Please try again later.');
    },
  });

  const onSubmit: React.FormEventHandler<HTMLFormElement> = e => {
    e.preventDefault();
    const form = new FormData(e.currentTarget);
    const content = form.get('content');
    if (typeof content !== 'string') return;
    mutate({ content });
  };

  if (!user) return null;

  return (
    <div className="flex items-center gap-4 border-b border-zinc-400 px-4 py-6 md:gap-6 md:px-6 md:py-8">
      <Image
        src={user.profileImageUrl}
        alt="Profile picture"
        className="h-10 w-10 rounded-full md:h-12 md:w-12"
        width={48}
        height={48}
      />
      <form
        ref={form}
        onSubmit={onSubmit}
        className="relative flex flex-grow items-center"
      >
        <input
          ref={input}
          type="text"
          name="content"
          placeholder="Type some emojis!"
          disabled={isPosting}
          className="w-full rounded-full border-none bg-gray-200 px-6 py-2 text-lg text-zinc-800 placeholder:text-sm placeholder:italic focus:bg-transparent focus:ring-zinc-400 dark:bg-zinc-800 dark:text-white dark:placeholder:text-zinc-400 md:px-8 md:py-3"
        />
        {isPosting && <Spinner size={24} className="absolute right-4" />}
      </form>
    </div>
  );
};

type PostWithUser = RouterOutputs['posts']['getAll'][number];
const PostView = ({ post, author }: PostWithUser) => {
  return (
    <li className="flex items-center gap-4 border-b border-zinc-400 p-4 md:gap-6 md:p-6">
      <Image
        src={author.profileImageUrl}
        alt={`${author.username}'s profile picture`}
        className="h-10 w-10 rounded-full md:h-12 md:w-12"
        width={48}
        height={48}
      />
      <div className="flex flex-col gap-1">
        <div className="flex items-center gap-x-1 text-sm text-zinc-500">
          <span className="font-medium">{`@${author.username}`}</span>
          <span>•</span>
          <span>{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <p className="text-xl md:text-2xl">{post.content}</p>
      </div>
    </li>
  );
};

const Feed = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading)
    return (
      <div className="absolute inset-0 grid place-items-center">
        <Spinner size={96} />
      </div>
    );

  if (!data)
    return (
      <div className="absolute inset-0 grid place-items-center">
        <p className="text-xl text-black dark:text-white">
          Something went wrong
        </p>
      </div>
    );

  return (
    <div>
      <ul className="flex flex-col">
        {data.map(row => (
          <PostView key={row.post.id} {...row} />
        ))}
      </ul>
    </div>
  );
};

const Home: NextPage = () => {
  // Start fetching asap
  api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Chirp T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="z-10 grid grid-cols-3 place-items-center bg-white px-6 py-4 drop-shadow-md dark:border-b dark:border-zinc-400 dark:bg-zinc-950 dark:drop-shadow-none md:py-6">
        <span>&nbsp;</span>
        <h1 className="font-mono text-lg font-bold uppercase text-black dark:text-white md:text-2xl">
          Chirp T3
        </h1>
        <div className="place-self-end">
          <SignedOut>
            <SignInButton mode="modal">
              <button className="rounded bg-zinc-900 px-3 py-1 font-mono text-sm font-medium text-white hover:bg-zinc-700 dark:bg-zinc-50 dark:text-black dark:hover:bg-zinc-200 md:px-4 md:text-base">
                Sign in
              </button>
            </SignInButton>
          </SignedOut>
          <SignedIn>
            <UserButton
              appearance={{
                elements: {
                  userButtonAvatarBox: 'w-10 h-10',
                },
              }}
            />
          </SignedIn>
        </div>
      </header>

      <div className="flex flex-1 justify-center bg-gradient-to-b from-white to-zinc-100 px-6 dark:from-zinc-950 dark:to-zinc-950">
        <main className="relative w-full border-x border-zinc-400 md:max-w-3xl">
          <div>
            <SignedIn>
              <CreatePostWizard />
            </SignedIn>
          </div>

          <Feed />
        </main>
      </div>
    </>
  );
};

export default Home;
